region            = "us-east-1"
cluster_name      = "ad-app"
instance_type     = "t2.micro"
#nginx_image_ref   = "williaumwu/ms-nginx:app"
#get_image_ref     = "williaumwu/ms-app:get"
#post_image_ref    = "williaumwu/ms-app:post"
